CA-ASP.NET-MVC-Project-master/CA-College/CA-Gym/CA-Gym/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CA_Gym.Controllers
{
    public class ContactController : Controller
    {
        static DataSet ds;
        static DataTable dt;

        public ActionResult Contact()
        {
            if (System.IO.File.Exists(Server.MapPath("~/App_Data/contact.xml")))
            {
                ds = new DataSet();
                ds.ReadXml(Server.MapPath("~/App_Data/contact.xml"));
                dt = ds.Tables["user_contact"];
            }
            else
            {
                ds = new DataSet("contact");
                dt = new DataTable("user_contact");
                DataColumn name_col = new DataColumn("name");
                DataColumn email_col = new DataColumn("email");
                DataColumn comments_col = new DataColumn("comments");
                dt.Columns.Add(name_col);
                dt.Columns.Add(email_col);
                dt.Columns.Add(comments_col);
                ds.Tables.Add(dt);
            }
            return View();
        }

        [HttpPost]
        public ActionResult Contact(string name, string email, string comments)
        {
            if (ModelState.IsValid)
            {
                DataRow row = dt.NewRow();
                row["name"] = name;
                row["email"] = email;
                row["comments"] = comments;
                dt.Rows.Add(row);
                ds.AcceptChanges();
                ds.WriteXml(Server.MapPath("~/App_Data/contact.xml"));
                return View("StatusC");
            }

            else return View("Index");
        }
    }
}

CA-ASP.NET-MVC-Project-master/CA-College/CA-Gym/CA-Gym/Controllers/TrainersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CA_Gym.Models;

namespace CA_Gym.Controllers
{
    public class TrainersController : Controller
    {
        DAO dao = new DAO();
        // GET: Trainers
        public ActionResult Trainers()
        {
            return View();
        }

        [HttpGet]
        public ActionResult AddTrainer()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddTrainer(Trainer trainer)
        {
            int count = 0;
            if (ModelState.IsValid)
            {
                count = dao.Insert(trainer);
                //Response.Write(dao.message);
                if (count == 1)
                    ViewBag.Status = "User is created successfully.";
                else
                {
                    ViewBag.Status = "Error! " + dao.message;
                }
                return View("Status");
            }
            return View(trainer);
        }
    }
}

CA-ASP.NET-MVC-Project-master/CA-College/CA-Gym/CA-Gym/Views/Shared/_layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="A 24 hour gym, with great nutrition and excercise tips">
    <meta name="keywords" content="Gym, fitness, weights, nutrition, health,exercise, training  ">
    <meta name="author" content="Jim">
    @*<meta http-equiv="X-UA-Compatible" content="ie=edge">*@
    
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.2.0/ekko-lightbox.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/flaticon.css"> 
    <link rel="stylesheet" href="~/Content/style.css">
    <title>Jim's Gym</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    @Html.ActionLink("Jim's Gym", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        @if (Session["id"] == null)
        {
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    @Html.ActionLink("Home", "Index", "Home", null, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Prices", "Prices", "Prices", null, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Facilities", "Facilities", "Facilities", null, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Classes", "Classes", "Classes", null, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Exercise", "Exercise", "Exercise", null, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Nutrition", "Nutrition", "Nutrition", null, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Meet Our Trainers", "Trainers", "Trainers", null, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Contact Us", "Contact", "Contact", null, new { @class = "nav-link" })
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">

                <li class="nav-item">
                    @Html.ActionLink("Login", "Login", "User", null, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Register", "MemberType", "User", null, new { @class = "nav-link" })
                </li>
            </ul>
        }
        else if (Session["id"].ToString() == "Member")
        {
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    @Html.ActionLink("Classes", "Classes", "Classes", null, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Exercise", "Exercise", "Exercise", null, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Nutrition", "Nutrition", "Nutrition", null, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Meet Our Trainers", "Trainers", "Trainers", null, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Book a Class", "AddBooking", "Classes", null, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Book a PT Session", "AddPTSession", "Classes", null, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Create Nutrition Blog Post", "NutritionBlog", "Nutrition", null, new { @class = "nav-link" })
                </li>
                
            </ul>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    @Html.ActionLink("Logout", "Logout", "User", null, new { @class = "nav-link" })
                </li>
            </ul>
        }
        else
        {
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    @Html.ActionLink("AddTrainer", "AddTrainer", "Trainers", null, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("AddClasses", "AddClass", "Classes", null, new { @class = "nav-link" })
                </li>
                
             </ul>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    @Html.ActionLink("Logout", "Logout", "User", null, new { @class = "nav-link" })
                </li>
            </ul>
        }
</div>
</nav>
    

        
    

    

    @RenderBody()
    <footer id="main-footer" class="text-center p-4 footer">
        <div class="container">
            <div class="row">
                <div class="col">
                    <p>Copyright &copy; 2017 Jim's Gym</p>
                    
                </div>
            </div>
        </div>
    </footer>



    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.2.0/ekko-lightbox.js"></script>
    @*<script src="js/navbar-fixed.js"></script>*@
    <script src="~/Scripts/main.js"></script>
</body>

</html>