CA-ASP.NET-MVC-Project-master/CA-College/CA-Gym/CA-Gym/Models/Trainer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CA_Gym.Models
{
    public class Trainer
    {
        public string Name { get; set; }
        public int Age { get; set; }
        public string Gender { get; set; }
        public string Speciality { get; set; }

        public Trainer()
        {

        }

        public Trainer(string n, int a, string gen, string spec)
        {
            Name = n;
            Age = a;
            Gender = gen;
            Speciality = spec;
        }

    }
}

CA-ASP.NET-MVC-Project-master/CA-College/CA-Gym/CA-Gym/Controllers/ClassesController.cs
using CA_Gym.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CA_Gym.Controllers
{
    public class ClassesController : Controller
    {
        DAO dao = new DAO();
        // GET: Classes
        public ActionResult Classes()
        {
            List<Class> classList = dao.ShowAllClasses();
            return View(classList);
        }

        [HttpGet]
        public ActionResult AddClass()
        {
            string response = null;
            ViewBag.TrainerList = dao.GetTrainerName();
            //ViewBag.TrainerID = dao.getTrainerIDFromDropDown();
            //response = dao.getTrainerIDFromDropDown();
            //Response.Write(response.Count());
            return View();
        }

        [HttpPost]
        public ActionResult AddClass(Class c)
        {
            string t = Request.Form["TrainerList"].ToString();
            ViewBag.TitleList = dao.GetTrainerName();
            int trainerID = dao.getTrainerIDFromDropDown(t);
            int count = 0;
            if (ModelState.IsValid)
            {
                count = dao.Insert(c, trainerID);
                //Response.Write(dao.message);
                if (count == 1)
                    ViewBag.Status = "Class is created successfully.";
                else
                {
                    ViewBag.Status = "Error! " + dao.message;
                }
                return View("Status");

            }
            return View(c);
        }

        [HttpGet]
        public ActionResult AddBooking()
        {
            ViewBag.ClassList = dao.GetClassType();

            return View();
        }

        [HttpPost]
        public ActionResult AddBooking(Booking b)
        {
            int memberID = dao.getMemberIDFromSession(Session["email"].ToString());

            string c = Request.Form["ClassList"].ToString();
            int classID = dao.getClassIDFromDropDown(c);
            string classTime = dao.getClassTimeFromDropDown(c);

            int count = 0;
            if (ModelState.IsValid)
            {
                count = dao.Insert(b, memberID, classID, classTime);
                //Response.Write(dao.message);
                if (count == 1)
                    ViewBag.Status = "Booking has been made successfully.";
                else
                {
                    ViewBag.Status = "Error! " + dao.message;
                }
                return View("StatusBook");

            }
            return View(b);
        }

        [HttpGet]
        public ActionResult AddPTSession()
        {
            ViewBag.TrainerList = dao.GetTrainerName();
            ViewBag.LocationList = dao.GetGymLocation();
            ViewBag.HourList = new List<int> { 1, 2, 3, 4};
            ViewBag.TypeList = new List<string> {"Strength","Cardio","Yoga","Pilates","Mobility", "Specialised"};

            return View();
        }

        [HttpPost]
        public ActionResult AddPTSession(PTSession pt)
        {
            string t = Request.Form["TrainerList"].ToString();
            string g = Request.Form["LocationList"].ToString();
            string type = Request.Form["TypeList"].ToString();
            string hour = Request.Form["HourList"].ToString();
            int c = int.Parse(hour) * 20;

            int count = 0;

            pt.TrainerID = dao.getTrainerIDFromDropDown(t);
            pt.MemberID = dao.getMemberIDFromSession(Session["email"].ToString());
            pt.SessLocation = g;
            pt.SessionLength = hour + " hour(s)";
            pt.SessType = type;
            pt.Cost = c;

            if (ModelState.IsValid)
            {
                count = dao.Insert(pt);
                //Response.Write(dao.message);
                if (count == 1)
                    ViewBag.Status = "PT Session has been successfully booked.";
                else
                {
                    ViewBag.Status = "Error! " + dao.message;
                }
                return View("StatusPT");

            }
            return View(pt);
        }
    }
}

CA-ASP.NET-MVC-Project-master/CA-College/CA-Gym/CA-Gym/Controllers/TrainersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CA_Gym.Models;

namespace CA_Gym.Controllers
{
    public class TrainersController : Controller
    {
        DAO dao = new DAO();
        // GET: Trainers
        public ActionResult Trainers()
        {
            return View();
        }

        [HttpGet]
        public ActionResult AddTrainer()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddTrainer(Trainer trainer)
        {
            int count = 0;
            if (ModelState.IsValid)
            {
                count = dao.Insert(trainer);
                //Response.Write(dao.message);
                if (count == 1)
                    ViewBag.Status = "User is created successfully.";
                else
                {
                    ViewBag.Status = "Error! " + dao.message;
                }
                return View("Status");
            }
            return View(trainer);
        }
    }
}

CA-ASP.NET-MVC-Project-master/CA-College/CA-Gym/CA-Gym/Views/Trainers/AddTrainer.cshtml
@model CA_Gym.Models.Trainer
@{
    ViewBag.Title = "AddTrainer";
    Layout = "~/Views/Shared/_layout.cshtml";
}

<div class="container">
    <div class="row justify-content-center mt-3 mb-5">
        <div class="col-md-6 offset-md-3">
            @using (Html.BeginForm("AddTrainer", "Trainers", FormMethod.Post))
            {
                <form class="form-group ">
                    <h2 class="display-4 py-3 mt-4">Add New Trainer</h2>
                    @Html.ValidationSummary(false, "", new { @class = "error" })

                    <div class="form-group row">
                        @Html.LabelFor(u => u.Name, new { @class = "col-md-4 col-form-label" })
                        <div class="col-md-8">
                            @Html.TextBoxFor(u => u.Name, new { @class = "form-control" })
                        </div>
                    </div>
                    
                    <div class="form-group row">
                        @Html.LabelFor(u => u.Age, new { @class = "col-md-4 col-form-label" })
                        <div class="col-md-8">
                            @Html.TextBoxFor(u => u.Age, new { @class = "form-control" })
                        </div>
                    </div>

                    <div class="form-group row">
                        @Html.LabelFor(u => u.Gender, new { @class = "col-md-4 col-form-label" })
                        <div class="col-md-8">
                            @Html.TextBoxFor(u => u.Gender, new { @class = "form-control" })
                        </div>
                    </div>

                    <div class="form-group row">
                        @Html.LabelFor(u => u.Speciality, new { @class = "col-md-4 col-form-label" })
                        <div class="col-md-8">
                            @Html.TextBoxFor(u => u.Speciality, new { @class = "form-control" })
                        </div>
                    </div>

                    <input id="Submit1" type="submit" value="Add Trainer" class="btn btn-success mt-3 mb-5 mr-3" />
                    <input id="Reset1" type="reset" value="Clear Form" class="btn btn-danger mt-3 mb-5 " />

                </form>
            }
        </div>
    </div>
    
</div>

CA-ASP.NET-MVC-Project-master/CA-College/CA-Gym/CA-Gym/Views/Trainers/Status.cshtml
@{
    ViewBag.Title = "Status";
    Layout = "~/Views/Shared/_layout.cshtml";
}
<div class="container">
    <div class="row justify-content-center mt-5 pt-5">
        <div class="col-md-8">
            <h2 class="display-4 text-center">@ViewBag.Status</h2>
            @Html.ActionLink("Add Another Trainer", "AddTrainer", "Trainers", null, new { @class = "btn btn-success btn-lg btn-block mt-5" })
        </div>
    </div>
</div>

CA-ASP.NET-MVC-Project-master/CA-College/CA-Gym/CA-Gym/Views/Trainers/Trainers.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_layout.cshtml";
}

<section id="gallery" class="py-5">
    
    <div class="container">
        <div class="text-center">
            <h1 class="text-center pt-0">Our Trainers</h1>
            <p class="text-center">Personal trainers can help produce a training plan built around your abilities and timeframe. They can help with motivation and nutrition.</p

                <button class="btn btn-success"></button>
                @if (Session["id"] == null)
                {
                    @Html.ActionLink("Book Now", "Login", "User", null, new { @class = "btn btn-primary" })
                }
                else
                {
                    @Html.ActionLink("Book Now", "AddPtSession", "Classes", null, new { @class = "btn btn-primary" })
                }
</div>
        
        <div class="row mt-5">
            <div class="col-md-4 mb-4"> 

                <div class="card border-0 text-white text-center">
                    <a href="~/Content/Images/person1.jpg" data-toggle="lightbox" data-gallery="img-gallery">
                        <img src="~/Content/Images/person1.jpg" class="img-fluid" alt="">
                    </a>
                    <div class="card-img-overlay ">
                        <h2 class="card-text  display-4">Simon Flynn</h2>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card border-0 text-white text-center">
                    <a href="~/Content/Images/person2.jpg" data-toggle="lightbox" data-gallery="img-gallery">
                        <img src="~/Content/Images/person2.jpg" class="img-fluid" alt="">
                    </a>
                    <div class="card-img-overlay ">
                        <h2 class="card-text  display-4">Colm Griffin</h2>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card border-0 text-white text-center">
                    <a href="~/Content/Images/person3.jpg" data-toggle="lightbox" data-gallery="img-gallery">
                        <img src="~/Content/Images/person3.jpg" class="img-fluid" alt="">
                    </a>
                    <div class="card-img-overlay ">
                        <h2 class="card-text  display-4">David Brien</h2>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-4">
                <div class="card border-0 text-white text-center">
                    <a href="~/Content/Images/person4.jpg" data-toggle="lightbox" data-gallery="img-gallery">
                        <img src="~/Content/Images/person4.jpg" class="img-fluid" alt="">
                    </a>
                    <div class="card-img-overlay ">
                        <h2 class="card-text  display-4">Tim Dalton</h2>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card border-0 text-white text-center">
                    <a href="~/Content/Images/person5.jpg" data-toggle="lightbox" data-gallery="img-gallery">
                        <img src="~/Content/Images/person5.jpg" class="img-fluid" alt="">
                    </a>
                    <div class="card-img-overlay ">
                        <h2 class="card-text  display-4">Mark Flynn</h2>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card border-0 text-white text-center">
                    <a href="~/Content/Images/person6.jpg" data-toggle="lightbox" data-gallery="img-gallery">
                        <img src="~/Content/Images/person6.jpg" class="img-fluid" alt="">
                    </a>
                    <div class="card-img-overlay ">
                        <h2 class="card-text  display-4">Adam North</h2>
                    </div>
                </div>
            </div>
        </div>

        <div class="row mt-5">
            <div class="col-md-4 mb-4">
                <div class="card border-0 text-white text-center">
                    <a href="~/Content/Images/person7.jpg" data-toggle="lightbox" data-gallery="img-gallery">
                        <img src="~/Content/Images/person7.jpg" class="img-fluid" alt="">
                    </a>
                    <div class="card-img-overlay ">
                        <h2 class="card-text  display-4">Jim Franklin</h2>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card border-0 text-white text-center">
                    <a href="~/Content/Images/person8.jpg" data-toggle="lightbox" data-gallery="img-gallery">
                        <img src="~/Content/Images/person8.jpg" class="img-fluid" alt="">
                    </a>
                    <div class="card-img-overlay ">
                        <h2 class="card-text  display-4">Tony Baldwin</h2>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card border-0 text-white text-center">
                    <a href="~/Content/Images/person9.jpg" data-toggle="lightbox" data-gallery="img-gallery">
                        <img src="~/Content/Images/person9.jpg" class="img-fluid" alt="">
                    </a>
                    <div class="card-img-overlay ">
                        <h2 class="card-text  display-4">Sean Hanson</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>